---
apiVersion: v1
kind: Service
metadata:
  name: scylla
  namespace: default
  labels:
    component: database
    environment: development
    name: scylla
spec:
  clusterIP: None
  selector:
    component: database
    environment: development
    name: scylla
  ports:
  - port: 9043
    protocol: TCP
    targetPort: 9043
